libraryDemo:
  transaction:
    namingStrategy: uuid

spring:
  application:
    name: Demo Bibliothek
    
  #################################    
  # Datasource configuration
  #################################   
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: example
    password: example

  #################################    
  # H2 Console configuration
  #################################
  h2:
    console:
      enabled: true
      path: /h2-console

  #################################    
  # JPA and Hibernate configuration
  #################################
  jpa:
    hibernate.ddl-auto: create
    open-in-view: false
